# Generated by Django 3.2 on 2021-04-29 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=500)),
                ('job_type', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('fb_link', models.URLField()),
                ('wattsapp_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
        ),
    ]
