# Generated by Django 3.2 on 2021-05-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Team',
        ),
    ]
