# Generated by Django 3.2.3 on 2021-07-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
    ]
