# Generated by Django 3.2.3 on 2021-07-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_lab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='experiment_conclusion',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='experiment_materials',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='experiment_objective',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='experiment_steps',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
